### ISSUE TITLE
Add parameter old to relfect function and drop the withOld syntax

### ISSUE THREAD

**Issue by opensas** [PixievoltNo1/svelte-writable-derived#11]
Is there a reason why reflect couldn't just be a function receiving the following params?

- `reflecting`: the new value of the derived (child) store
- `old`: the current value of the origin (parent) store
- `set`: a function to update the origin (parent) store

In those cases where the `old` param is not needed (like in [this](https://github.com/PixievoltNo1/svelte-writable-derived#making-an-object-store-from-a-json-string-store) example) it could just be ignored.

The syntax would be easier and more simple to remember. and the following example:

```
let item0Store = writableDerived(arrayStore, 
	$arrayStore => $arrayStore[0], // update derived from origin
	{ withOld: (reflecting, old) => old[0] = reflecting } // update origin from derived (underive)
)
```

could be simplified to:

```
let item0Store = writableDerived(arrayStore, 
	$arrayStore => $arrayStore[0], // update derived from origin
	(reflecting, old) => old[0] = reflecting // update origin from derived (underive)
)
```

More over, for backward compatibility reasons the current `withOld` form could still be supported, at least for a couple versions.

**Comment by PixievoltNo1** [comment]
The API is what it is for optimization reasons. To avoid extra subscribe/unsubscribe calls to the origin stores, this package keeps copies of origin values to pass to `reflect`. By requiring you to explicitly state if you will need those values, this package can avoid keeping those values if you don't, thus saving memory.

**Comment by opensas** [comment]
It makes sense, I'll have a look at the source code to better understand how everythingis working.

Just for the record, if I really care about getting rid of the 'withOld' syntax, I can always create a helper function like this:

```javascript
	const myWritableDerived = (origins, derive, reflect, initial) => {
		return writableDerived(origins, derive, { withOld: reflect }, initial)
	}
```

**Comment by PixievoltNo1** [comment]
Thought you'd like to know I've proposed (#23) to remove async reflect and simplify `reflect` to `(reflecting, old)`.
