### ISSUE TITLE
Add an example using propertyStore to handle arrays and deep level objects mixed with arrays

### ISSUE THREAD

**Issue by opensas** [PixievoltNo1/svelte-writable-derived#12]
It's really surprising that things like these work ok using the `propertyStore` helper function as is:

```
let arrayStore = writable([
	{ name: 'Josh', pets: [ { kind: 'cow', name: 'mooo' }, { kind: 'cat', name: 'tom' } ] }, 
	{ name: 'Jonh', pets: [ { kind: 'dog', name: 'fido' }, { kind: 'snake', name: 'pssssss' } ] }, 
])
let johnFirstPetNameStore = propertyStore(arrayStore, [1, 'pets', 0, 'name'])
```

I think an example like that in the readme would be very useful, taking into account that the name of the helper function might make you think that it only works with object properties.

Have a look at [this REPL](https://svelte.dev/repl/7410e50ba1974238b8aaf0a6c38836b7?version=3.44.1) for a more complete example.

**Comment by PixievoltNo1** [comment]
This was not an intended feature of `propertyStore`, but what the heck, I'll make it one. I'll also update the description of its parameters' types in the readme and JSDocs.

**Comment by opensas** [comment]
I suspected it, but yeah, it works really great and it's a super useful feature.

Here's a repl with the horse example rearranged to work with arrays, showing also how bind: works great with these stores: https://svelte.dev/repl/91cf06ad8adf4ff4abd116ef3526b7c0?version=3.44.1

**Comment by PixievoltNo1** [comment]
Version 2.1.2 is out with the updated documentation!
