### ISSUE TITLE
Clarification on subscription callback order w/ REPL example.

### ISSUE THREAD

**Issue by typhonrt** [PixievoltNo1/svelte-writable-derived#14]
Hi. 

I'm interested in using `svelte-writable-derived`, but am a little unclear on a symptom that I am seeing. I have setup a basic test case up in the REPL here: <https://svelte.dev/repl/f5de5423133d4c4eb31812f60e436bb1?version=3.44.3>

In `./store.js` I create a writable store for the `options` object. Then return a custom store with the subscribe method of the writable along with two entries `test` which is a `writableDerived` instance and `test2` which is a `propertyStore` instance. 

In `App.svelte` I add two local subscriptions to the derived stores. In the console output you can see that the `writableDerived` update callback is occurring after the local subscription callbacks in `App.svelte`. The same thing is likely happening with `propertyStore`, but there is no way to log the call order. The `options` object is not updated before the local subscription callbacks as expected. In the display of data I use a timeout in both local store subscriptions to log the correct / expected values that are available on the next clock tick. This is displayed as `optionsString` and `optionsStringTimeout`. My assumption or expectation is that they would be the same which is not the case.

Are my assumptions wrong that the `writableDerived` callback should trigger before any other subscriptions to it thereby allowing `options` to be updated before other subscription callbacks? 

Thanks for the help..

**Comment by PixievoltNo1** [comment]
The order is already documented in [the section on `reflect`](https://github.com/PixievoltNo1/svelte-writable-derived#new-parameter-reflect) — "`reflect` is called after the derived store's subscriptions are called."

I'm marking this closed, but feel free to comment with any further concerns or requests.

**Comment by typhonrt** [comment]
Cool.. Just missed that aspect. I was able to restructure my use case to fit this pattern. Thanks for the quick reply.
