### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by PixievoltNo1** [PixievoltNo1/svelte-writable-derived#2]
I don't use TypeScript myself, but it appears popular in the wider Svelte community. I'd appreciate getting a definition file that would provide type annotations for TypeScript users.

**Comment by PixievoltNo1** [comment]
JSDocs were added in the recent v2.1.0 release, providing partial TypeScript support, but I'm still interested in a more complete solution. In addition to accepting pull requests, I'm now offering to work on this myself in exchange for [sponsoring me](https://sponsus.org/u/pixievoltno1).

**Comment by typhonrt** [comment]
If interested I have a recent utility NPM package that generates TS declarations from ESM source code. You can easily setup an NPM script to generate the types via the `prepublishOnly` script or whatever is clever. 

The package is here: [@typhonjs-build-test/esm-d-ts](https://github.com/typhonjs-node-build-test/esm-d-ts). 

The package itself uses the [NPM script method](https://github.com/typhonjs-node-build-test/esm-d-ts/blob/main/package.json#L61)

I haven't bumped this package to "beta" yet, but it is working well and makes it easy to generate TS declarations from ESM source.

**Comment by PixievoltNo1** [comment]
@typhonrt I'm not clear on how that's an improvement over the status quo. TypeScript can directly use the existing JSDocs.

**Comment by typhonrt** [comment]
You can set a types field in `package.json` pointing to the `d.ts` file. This will show up on NPM as the package having TS definitions. Small benefit there. 

Not that this applies for your package, but if you are bundling a package with Rollup, etc. providing the `d.ts` file is useful in that case. That is particularly why I built the tool.

**Comment by PixievoltNo1** [comment]
Released in version 2.1.3, thanks to @qu1ncyk! 🎉
