### ISSUE TITLE
Usage with Webpack 5: "Error: Default condition should be last one"

### ISSUE THREAD

**Issue by joelcieslar** [PixievoltNo1/svelte-writable-derived#21]
Using `svelte-writable-derived` with Webpack 5 results in this error:

```
Compiled with problems:

Module not found: Error: Default condition should be last one
```

I fixed this problem by modifying `package.json` to make the default condition the last one:

```
"exports": {
	".": {
		"types": "./index.d.ts",
		"default": "./index.mjs" // 👈 this should go last
	},
	"./package.json": "./package.json"
}
```

And now the error goes away. :partying_face:

**Comment by PixievoltNo1** [comment]
Published version 2.1.5 with that change. Thanks for the report!
