### ISSUE TITLE
[small mod] Type declarations - export type aliases.

### ISSUE THREAD

**Issue by typhonrt** [PixievoltNo1/svelte-writable-derived#24]
Thanks @PixievoltNo1 for updating `writable-derived` for Svelte v4 out of the gate as this is very helpful!

I gather the `index.d.ts` for this package is hand generated? I think there is value in exporting the type aliases. This is a simple change just adding export before the `type` as follows:

```ts
/** The minimal requirements of the
 * [writable store contract](https://svelte.dev/docs#component-format-script-4-prefix-stores-with-$-to-access-their-values-store-contract).
 */
export type MinimalWritable<T> = Pick<Writable<T>, "set" | "subscribe">;

/** Stores that may be used as origins. */
export type Stores = MinimalWritable<any> | [Readable<any>, ...Array<Readable<any>>] | Array<Readable<any>>;

/** Values retrieved from origin stores. */
export type StoresValues<T> = T extends Readable<infer U> ? U :
    { [K in keyof T]: T[K] extends Readable<infer U> ? U : never };

/** Values sent to origin stores. */
export type SetValues<T> = T extends MinimalWritable<infer U> ? U :
    { [K in keyof T]?: T[K] extends MinimalWritable<infer U> ? U : never };
```

**Comment by PixievoltNo1** [comment]
I'm not convinced that would be valuable. TypeScript doesn't care that types match exactly, only that they're compatible, so your values just need to fit the constraints specified by the types. I note Svelte doesn't expose its own Stores and StoresValues.

I'm concerned that exposing them could lead to package consumers becoming dependant on things that are only tangentially related to the purpose of the package.

**Comment by typhonrt** [comment]
I definitely appreciate your discernment in keeping things clean. The direction I'm coming from is API doc creation. I generate API docs via TypeDoc from declarations for my larger runtime library. I do re-export `writatble-derived` as part of this larger integrated framework and include the types. 

Technically, there is no direct issue as I have a ESM -> DTS tool where I can modify your types as I bundle where I do export the non-exported types. I have my own DTS generation tool; [esm-d-ts](https://www.npmjs.com/package/@typhonjs-build-test/esm-d-ts)

Here is what writable-derived looks like w/ the types exported from a documentation perspective:
[Main sub-path export](https://typhonjs-fvtt-lib.github.io/api-docs/modules/_runtime_svelte_store_writable_derived.html)

And for [propertyStore](https://typhonjs-fvtt-lib.github.io/api-docs/functions/_runtime_svelte_store_writable_derived.propertyStore.html) you can see how the `origin` parameter is clearly understood in the docs because `MinimalWritable` is available / exported in my version of the types for `writable-derived`.

Just something to consider re: for documentation purposes and not just pure TS consumption.

As far as tidy types go though you could probably just use `import type { StoreValues } from 'svelte/store';` instead of duplicating that type alias from Svelte. 

So again no worries. I just am trying to remove any special handling of re-exported modules in my library. What I brought up is useful in the context of API doc generation.

**Comment by PixievoltNo1** [comment]
I've decided to reject this, between my concern stated earlier, Svelte developers more experienced in TypeScript choosing not to expose similar types from `svelte/store`, and you already having a solution that's working for your needs. Thanks for understanding.
