### ISSUE TITLE
Fix writableDerived typescript signature

### ISSUE THREAD

**Issue by svenk** [PixievoltNo1/svelte-writable-derived#25]
The `update` signature in https://github.com/PixievoltNo1/svelte-writable-derived/blob/master/index.d.ts#L43 is wrong and described as `Updater<T>` while it should read `(fn: Updater<T>) => void` as in https://svelte.dev/docs/svelte-store#derived

That is, the line

```ts
export default function writableDerived<S extends Stores, T>(
    origins: S,
    derive: (values: StoresValues<S>, set: (value: T) => void, update: Updater<T>) => void,
    reflect: (reflecting: T, old: StoresValues<S>) => SetValues<S>,
    initial?: T
): Writable<T>;
```

should read

```ts
export function writableDerived<S extends Stores, T>(
  origins: S,
  derive: (values: StoresValues<S>, set: (value: T) => void, update: (fn: Updater<T>)=>void) => void,
  reflect: (reflecting: T, old: StoresValues<S>) => SetValues<S>,
  initial?: T
): Writable<T>;
```

The actual implementation is right, it is only an error in the `index.t.ts` resulting in TypeScript complaining about wrong types when using this signature.

**Comment by PixievoltNo1** [comment]
Fix released in version 3.1.1. Thanks for the report!
