### ISSUE TITLE
Nested property shorthand syntax

### ISSUE THREAD

**Issue by thgh** [PixievoltNo1/svelte-writable-derived#5]
Today I came across this usecase:
```svelte
<input type="checkbox" bind:value={$items} />

<script>
const existingStore = writable({ items: [] })
const items = writableDerived(mainstore, 'items') // I wish this syntax was supported
</script>
```

What do you think about supporting this syntax?

**Comment by PixievoltNo1** [comment]
Hello from the new username! Apologies for my silence, but I did decide to implement a variation on this idea. In keeping with the Svelte philosophy of "if you don't use it, you shouldn't pay for it", I've implemented this as a separate exported function, so it can be tree-shaken out by consumers who don't need it. It'll be in version 2.1.0, to be published shortly. Look for `propertyStore` in the readme!
